update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release to TestFlight"
  lane :beta do
    ensure_git_status_clean

    changelog_from_git_commits(
      pretty: "- (%ae) %s",
      date_format: "short",
      merge_commit_filtering: "exclude_merges",
    )

    increment_build_number(xcodeproj: "Runner.xcodeproj")
    commit_version_bump(xcodeproj: "Runner.xcodeproj")
    add_git_tag
    push_to_git_remote

    match(type: "appstore")

    sh "cd ../.. && flutter build ios --release --no-codesign"
    build_ios_app(
      workspace: 'Runner.xcworkspace',
      scheme: 'Runner',
      export_method: "app-store",
    )

    upload_to_testflight

    notification(
      title: "TravelR",
      message: "TravelR iOS beta build finished",
    )
    slack(
      message: "Successfully distributed a new iOS beta build",
      slack_url: "https://hooks.slack.com/services/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",
    )
  end
end
