update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release to TestFlight"
  lane :beta do
    ensure_git_status_clean

    #increment_build_number(xcodeproj: "Runner.xcodeproj")
    #commit_version_bump(xcodeproj: "Runner.xcodeproj")
    #add_git_tag
    #push_to_git_remote

    get_certificates
    get_provisioning_profile
    sh "cd ../.. && flutter build ios --release --no-codesign"
    build_ios_app(
      workspace: 'Runner.xcworkspace',
      scheme: 'Runner',
    )

    changelog_from_git_commits
    upload_to_testflight

    notification(
      title: "TravelR",
      message: "TravelR beta build finished",
    )
    slack(
      message: "Successfully distributed a new beta build",
    )
  end
end
