update_fastlane

default_platform(:android)

platform :android do
  desc "Push a new release to internal testing"
  lane :internal do
    ensure_git_status_clean

    versionCode = sh("grep versionCode ../app/build.gradle | sed 's/.*versionCode //g' | tr -d '\\n'")
    changelog_from_git_commits(
      between: ["builds/androidinternal/#{versionCode}", "HEAD"],
      pretty: "- %h %an (%ae): %s",
      date_format: "short",
      merge_commit_filtering: "exclude_merges",
    )

    sh %Q{echo "$(awk '{sub(/versionCode [[:digit:]]+$/,"versionCode "$2+1)}1' ../app/build.gradle)" > ../app/build.gradle}
    versionCode = sh("grep versionCode ../app/build.gradle | sed 's/.*versionCode //g' | tr -d '\\n'")
    sh "git add ../app/build.gradle && git commit -m 'Version bump to #{versionCode}'"
    add_git_tag(build_number: versionCode)
    push_to_git_remote

    sh "cd ../.. && flutter build apk --release"

    upload_to_play_store(
        track: 'internal',
        apk: '../build/app/outputs/apk/release/app-release.apk'
    )

    notification(
      title: "TravelR",
      message: "TravelR Android beta build finished",
    )
    slack(
      message: "Successfully distributed a new Android beta build",
      slack_url: "https://hooks.slack.com/services/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",
    )
  end
end
